import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    'icons/index': 'src/icons/index.ts',
  },
  format: ['esm', 'cjs'],
  dts: true,
  sourcemap: false,
  external: [
    'react',
    'react-dom',
    'next',
    'next/image',
    'next/link',
    'next/dynamic',
    'classnames',
    'framer-motion',
    'swiper',
    'swiper/react',
    'swiper/modules',
    'swiper/css',
    'react-hook-form',
    'react-international-phone',
    'react-apexcharts',
    'apexcharts',
    'libphonenumber-js',
    '@dnd-kit/core',
    '@dnd-kit/sortable',
    '@dnd-kit/utilities',
    '@tanstack/react-virtual',
    '@tiptap/core',
    '@tiptap/react',
    '@tiptap/starter-kit',
    '@xyflow/react',
  ],
  clean: true,
  treeshake: true,
});
