import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    'icons/index': 'src/icons/index.ts',
    '3d/index': 'src/3d/index.ts',
    'charts/index': 'src/charts/index.ts',
  },
  format: ['esm', 'cjs'],
  dts: true,
  sourcemap: false,
  external: [
    'react',
    'react-dom',
    'next',
    'next/image',
    'next/link',
    'next/dynamic',
    'classnames',
    'framer-motion',
    'swiper',
    'swiper/react',
    'swiper/modules',
    'swiper/css',
    'react-hook-form',
    'react-international-phone',
    'libphonenumber-js',
    '@dnd-kit/core',
    '@dnd-kit/sortable',
    '@dnd-kit/utilities',
    '@tanstack/react-virtual',
    '@tiptap/core',
    '@tiptap/extension-code-block-lowlight',
    '@tiptap/extension-image',
    '@tiptap/extension-mention',
    '@tiptap/pm',
    '@tiptap/pm/state',
    '@tiptap/pm/view',
    '@tiptap/react',
    '@tiptap/starter-kit',
    '@tiptap/suggestion',
    '@xyflow/react',
    'lowlight',
    'three',
    'three/*',
    '@react-three/fiber',
    '@react-three/drei',
    'react-force-graph-3d',
    'react-resizable-panels',
  ],
  clean: true,
  treeshake: true,
});
