export type VariantTypoTags = 'h1' | 'h2' | 'h3' | 'h4' | 'p' | 'span' | 'label';

export type VariantTypoTagsStyles =
  | 'BodyXL'
  | 'BodyL'
  | 'BodyM'
  | 'BodyS'
  | 'BodyXS'
  | 'Labels'
  | 'LabelsS'
  | 'Info'
  | 'InfoBold'
  | 'Buttons'
  | 'ButtonsSemibold'
  | 'ButtonsS'
  | 'ButtonsSBold'
  | 'ButtonsBold'
  | 'M3HeadlineSmall'
  | 'MetricsTitle'
  | 'MetricsXL'
  | 'TabInfoTitle'
  | 'HeroSubtitle'
  | 'DisplayXL'
  | 'DisplayL'
  | 'SectionTitleL'
  | 'SectionTitleM'
  | 'SectionTitleS';

export type VariantTypoColors =
  | 'text-black_1'
  | 'text-black_2'
  | 'text-black_3'
  | 'text-black_4'
  | 'text-grey_1'
  | 'text-grey_2'
  | 'text-grey_3'
  | 'text-grey_4'
  | 'text-white_1'
  | 'text-white_2'
  | 'text-white_3'
  | 'text-white_4'
  | 'text-white'
  | 'text-pr_purple'
  | 'text-sec_purple'
  | 'text-pr_blue'
  | 'text-sec_blue'
  | 'text-error'
  | 'text-warning'
  | 'text-success'
  | 'text-current';
