export type VariantTypoIconName = 'users' | 'calendar' | 'job' | 'salary' | 'location';

export type VariantTypoColorsText =
  | 'text-black_1'
  | 'text-black_2'
  | 'text-black_3'
  | 'text-black_4'
  | 'text-grey_1'
  | 'text-grey_2'
  | 'text-grey_3'
  | 'text-grey_4'
  | 'text-white_1'
  | 'text-white_2'
  | 'text-white_3'
  | 'text-white_4'
  | 'text-white'
  | 'text-pr_purple'
  | 'text-sec_purple'
  | 'text-pr_blue'
  | 'text-sec_blue'
  | 'text-error'
  | 'text-warning'
  | 'text-success';

export type VariantTypoColorsCircle =
  | 'bg-black_1'
  | 'bg-black_2'
  | 'bg-black_3'
  | 'bg-black_4'
  | 'bg-grey_1'
  | 'bg-grey_2'
  | 'bg-grey_3'
  | 'bg-grey_4'
  | 'bg-white_1'
  | 'bg-white_2'
  | 'bg-white_3'
  | 'bg-white_4'
  | 'bg-white'
  | 'bg-pr_purple'
  | 'bg-sec_purple'
  | 'bg-pr_blue'
  | 'bg-sec_blue'
  | 'bg-error'
  | 'bg-warning'
  | 'bg-success';
